/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/invoices/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Invoices
         * @description Accept one or more PDF files and enqueue them for processing.
         */
        post: operations["upload_invoices_api_invoices_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description List all invoices with optional filters and pagination.
         */
        get: operations["list_invoices_api_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice
         * @description Get a single invoice with its metadata and line items.
         */
        get: operations["get_invoice_api_invoices__invoice_id__get"];
        /**
         * Update Invoice
         * @description Update extracted invoice data (for user corrections).
         */
        put: operations["update_invoice_api_invoices__invoice_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Invoice
         * @description Mark an invoice as approved after user review.
         */
        post: operations["approve_invoice_api_invoices__invoice_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Invoice
         * @description Export an approved invoice to Excel and return the file.
         */
        post: operations["export_invoice_api_invoices__invoice_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice Status
         * @description Get current processing status of an invoice.
         */
        get: operations["get_invoice_status_api_invoices__invoice_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Return summary statistics for the dashboard.
         */
        get: operations["get_dashboard_stats_api_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processing-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Processing History
         * @description Return paginated processing history from invoice records.
         */
        get: operations["get_processing_history_api_processing_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiMeta */
        ApiMeta: {
            pagination?: components["schemas"]["PaginationMeta"] | null;
        };
        /** ApiResponse[ApproveResult] */
        ApiResponse_ApproveResult_: {
            data: components["schemas"]["ApproveResult"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[DashboardStats] */
        ApiResponse_DashboardStats_: {
            data: components["schemas"]["DashboardStats"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[InvoiceDetail] */
        ApiResponse_InvoiceDetail_: {
            data: components["schemas"]["InvoiceDetail"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[InvoiceStatusPayload] */
        ApiResponse_InvoiceStatusPayload_: {
            data: components["schemas"]["InvoiceStatusPayload"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[UpdateResult] */
        ApiResponse_UpdateResult_: {
            data: components["schemas"]["UpdateResult"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[UploadResult] */
        ApiResponse_UploadResult_: {
            data: components["schemas"]["UploadResult"];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[list[InvoiceSummary]] */
        ApiResponse_list_InvoiceSummary__: {
            /** Data */
            data: components["schemas"]["InvoiceSummary"][];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApiResponse[list[ProcessingHistoryRecord]] */
        ApiResponse_list_ProcessingHistoryRecord__: {
            /** Data */
            data: components["schemas"]["ProcessingHistoryRecord"][];
            meta?: components["schemas"]["ApiMeta"] | null;
        };
        /** ApproveResult */
        ApproveResult: {
            /** Id */
            id: string;
            status: components["schemas"]["InvoiceStatus"];
        };
        /** Body_upload_invoices_api_invoices_upload_post */
        Body_upload_invoices_api_invoices_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * ConfidenceLevel
         * @enum {string}
         */
        ConfidenceLevel: "high" | "medium" | "low";
        /** DashboardStats */
        DashboardStats: {
            /** Total Invoices */
            total_invoices: number;
            /** Processed Today */
            processed_today: number;
            /** Pending Review */
            pending_review: number;
            /** Approved */
            approved: number;
            /** Failed */
            failed: number;
            /** Processing */
            processing: number;
            /** Queued */
            queued: number;
            /** Uploaded */
            uploaded: number;
            /** Cancelled */
            cancelled: number;
            /** Exported */
            exported: number;
            /** Total Amount */
            total_amount?: number | null;
            /** Avg Processing Time Minutes */
            avg_processing_time_minutes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceDetail */
        InvoiceDetail: {
            /** Id */
            id: string;
            /** Invoice Id */
            invoice_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Total Amount */
            total_amount?: number | null;
            status: components["schemas"]["InvoiceStatus"];
            confidence?: components["schemas"]["ConfidenceLevel"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Line Items */
            line_items?: {
                [key: string]: unknown;
            }[];
            /** Original Filename */
            original_filename?: string | null;
            /** Stored Filename */
            stored_filename?: string | null;
            /** Processing Stage */
            processing_stage?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * InvoiceStatus
         * @enum {string}
         */
        InvoiceStatus: "uploaded" | "queued" | "processing" | "ready_for_review" | "failed" | "cancelled" | "approved" | "exported";
        /** InvoiceStatusPayload */
        InvoiceStatusPayload: {
            /** Id */
            id: string;
            status: components["schemas"]["InvoiceStatus"];
            /** Processing Stage */
            processing_stage?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** InvoiceSummary */
        InvoiceSummary: {
            /** Id */
            id: string;
            /** Invoice Id */
            invoice_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Total Amount */
            total_amount?: number | null;
            status: components["schemas"]["InvoiceStatus"];
            confidence?: components["schemas"]["ConfidenceLevel"] | null;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
            /** Has More */
            has_more: boolean;
        };
        /** ProcessingHistoryRecord */
        ProcessingHistoryRecord: {
            /** Id */
            id: string;
            /** Invoice Id */
            invoice_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Processed At */
            processed_at?: string | null;
            /** Total Amount */
            total_amount?: number | null;
            confidence?: components["schemas"]["ConfidenceLevel"] | null;
            status: components["schemas"]["InvoiceStatus"];
            /** Destination */
            destination?: string | null;
        };
        /** UpdateResult */
        UpdateResult: {
            /** Updated */
            updated: boolean;
            /** Modified Count */
            modified_count: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Results */
            results: components["schemas"]["UploadResultItem"][];
        };
        /** UploadResultItem */
        UploadResultItem: {
            /** Id */
            id?: string | null;
            /** File Id */
            file_id?: string | null;
            /** Filename */
            filename: string;
            status: components["schemas"]["InvoiceStatus"];
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_invoices_api_invoices_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_invoices_api_invoices_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UploadResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_invoices_get: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string | null;
                /** @description Filter by vendor name */
                vendor?: string | null;
                /** @description Search invoice number or vendor */
                search?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_InvoiceSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_api_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_InvoiceDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_invoice_api_invoices__invoice_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UpdateResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_invoice_api_invoices__invoice_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApproveResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_invoice_api_invoices__invoice_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_status_api_invoices__invoice_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_InvoiceStatusPayload_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DashboardStats_"];
                };
            };
        };
    };
    get_processing_history_api_processing_history_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ProcessingHistoryRecord__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
